apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: kafka-drop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092"